import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useOrganizationList, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const CreateFlashCard = () => {
  const { user } = useUser();
  const { organizationList } = useOrganizationList();

  if (!user) return null;

  return (
    <div className="flex w-full gap-4">
      <img
        src={user.profileImageUrl}
        alt="user profile image"
        className="h-20 w-20 rounded-full"
      />
      {organizationList &&
      organizationList[0]?.organization.name === "Admins" ? (
        <input
          placeholder="enter the word here"
          className="grow bg-transparent text-3xl outline-none"
        />
      ) : (
        <button type="button"> Play </button>
      )}
    </div>
  );
};
const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.wordcards.getAll.useQuery();

  if (isLoading) return <div>...Loading</div>;
  if (!data) return <div>No data was found....</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-purple-400 bg-fuchsia-300 md:max-w-2xl">
          <div className="justify-center border-b border-purple-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreateFlashCard />}
          </div>
          <div className="flex flex-col text-2xl ">
            {data?.map((card) => (
              <div className="border-b border-purple-400 p-8" key={card.id}>
                {card.word}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
